---
- hosts: localhost
  vars_files:
  - vars/config.yml
  - vars/creds.yml
  tasks:
    
    - name: "[KOMPONIST] Generating Directory for Production-Ready Files"
      ansible.builtin.file:
        name: "{{ komponist.deploy_dir }}"
        state: directory

    - name: "[KOMPONIST] Generating Configuration / Compose Files from Templates"
      include_tasks: "tasks/configure-{{ item }}.yml"
      with_items:
        - "{{ komponist.configuration.keys() }}"
