---
- name: Komponist Stack Generation Playbook
  hosts: localhost
  vars_files:
    - vars/config.yml
    - vars/creds.yml
  tasks:

    - name: "(KOMPONIST) Generating Directory for Production-Ready Files"
      ansible.builtin.file:
        name: "{{ komponist.deploy_dir }}"
        state: directory
        mode: "0755"

    - name: "(KOMPONIST) Generating Configuration / Compose Files from Templates"
      ansible.builtin.include_tasks: "tasks/configure-{{ item }}.yml"
      with_items:
        - "{{ komponist.configuration.keys() }}"

    - name: "(KOMPONIST) Validation and Generation of docker-compose.yml"
      block:
        - name: "(DockerCompose) Validating Docker Compose Services"
          ansible.builtin.command:
            cmd: docker compose {{ compose_files }} config --quiet
          args:
            chdir: "{{ komponist.deploy_dir }}"
          vars:
            compose_files: >-
              {{ komponist.configuration.keys() | map('regex_replace', '^(.*)$', ' -f docker-compose.\1.yml') | join | trim }}
          register: docker_compose_validity
          changed_when: docker_compose_validity.rc != 0

        - name: "(DockerCompose) Generating docker-compose.yml file if all services are valid"
          ansible.builtin.command:
            cmd: docker compose -p {{ komponist.configuration.project_name | default('komponist') }} {{ compose_files }} config -o docker-compose.yml
          args:
            chdir: "{{ komponist.deploy_dir }}"
          vars:
            compose_files: >-
              {{ komponist.configuration.keys() | map('regex_replace', '^(.*)$', ' -f docker-compose.\1.yml') | join | trim }}
          changed_when: docker_compose_validity.rc != 0
