---
- name: '(Traefik) Creating Deployment Specific Directory'
  ansible.builtin.file:
    name: "{{ komponist.deploy_dir }}/traefik/configurations"
    state: directory

- name: '(Traefik) Generating Traefik Configuration File'
  ansible.builtin.template:
    src: config/traefik/traefik.yml.j2
    dest: "{{ komponist.deploy_dir }}/traefik/traefik.yml"

- name: '(Traefik) Copying Configuration Files for Traefik'
  ansible.builtin.copy:
    src: templates/config/traefik/configurations/
    dest: "{{ komponist.deploy_dir }}/traefik/configurations/"
    remote_src: true

- name: '(Traefik) Generating Compose Service File for Deployment'
  ansible.builtin.template:
    src: services/docker-compose.traefik.yml.j2
    dest: "{{ komponist.deploy_dir }}/docker-compose.traefik.yml"