---
name: Integrity Tests with Ansible

on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".vscode/**"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.10"
          - "3.9"
          - "3.8"
    
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
      
      - name: Pull eclipse-mosquitto image
        run: docker pull eclipse-mosquitto:2.0.15

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install ansible and pip dependencies
        run: python -m pip install ansible docker passlib jsonschema
      
      - name: Install ansible.utils collection
        run: ansible-galaxy collection install ansible.utils

      - name: Generate the Default Komponist Stack
        run: ansible-playbook -vv generate_stack.yml
      
      - name: Test Integrity of Generated Directories
        run: ansible-playbook tests/test_generated_directories.yml
      
      - name: Test Integrity of Generated Files
        run: ansible-playbook tests/test_generated_files.yml

      - name: Test Schema Validation Checks for Generated Files
        run: ansible-playbook tests/test_schemas.yml
      
      - name: Test Content Checks for Generated Files for Mosquitto / Node-RED
        run: ansible-playbook tests/test_file_contents.yml